export const JAPANESE_ALPHABET = {
    hiragana: [
        [
            { kana: "あ", romaji: "a" },
            { kana: "い", romaji: "i" },
            { kana: "う", romaji: "u" },
            { kana: "え", romaji: "e" },
            { kana: "お", romaji: "o" },
        ],
        [
            { kana: "か", romaji: "ka" },
            { kana: "き", romaji: "ki" },
            { kana: "く", romaji: "ku" },
            { kana: "け", romaji: "ke" },
            { kana: "こ", romaji: "ko" },
        ],
        [
            { kana: "さ", romaji: "sa" },
            { kana: "し", romaji: "shi" },
            { kana: "す", romaji: "su" },
            { kana: "せ", romaji: "se" },
            { kana: "そ", romaji: "so" },
        ],
        [
            { kana: "た", romaji: "ta" },
            { kana: "ち", romaji: "chi" },
            { kana: "つ", romaji: "tsu" },
            { kana: "て", romaji: "te" },
            { kana: "と", romaji: "to" },
        ],
        [
            { kana: "な", romaji: "na" },
            { kana: "に", romaji: "ni" },
            { kana: "ぬ", romaji: "nu" },
            { kana: "ね", romaji: "ne" },
            { kana: "の", romaji: "no" },
        ],
        [
            { kana: "は", romaji: "ha" },
            { kana: "ひ", romaji: "hi" },
            { kana: "ふ", romaji: "fu" },
            { kana: "へ", romaji: "he" },
            { kana: "ほ", romaji: "ho" },
        ],
        [
            { kana: "ま", romaji: "ma" },
            { kana: "み", romaji: "mi" },
            { kana: "む", romaji: "mu" },
            { kana: "め", romaji: "me" },
            { kana: "も", romaji: "mo" },
        ],
        [
            { kana: "や", romaji: "ya" },
            null,
            { kana: "ゆ", romaji: "yu" },
            null,
            { kana: "よ", romaji: "yo" },
        ],
        [
            { kana: "ら", romaji: "ra" },
            { kana: "り", romaji: "ri" },
            { kana: "る", romaji: "ru" },
            { kana: "れ", romaji: "re" },
            { kana: "ろ", romaji: "ro" },
        ],
        [
            { kana: "わ", romaji: "wa" },
            null,
            null,
            null,
            { kana: "を", romaji: "wo" },
        ],
        [
            { kana: "ん", romaji: "n" },
            null,
            null,
            null,
            null,
        ],
    ],

    katakana: [
        [
            { kana: "ア", romaji: "a" },
            { kana: "イ", romaji: "i" },
            { kana: "ウ", romaji: "u" },
            { kana: "エ", romaji: "e" },
            { kana: "オ", romaji: "o" },
        ],
        [
            { kana: "カ", romaji: "ka" },
            { kana: "キ", romaji: "ki" },
            { kana: "ク", romaji: "ku" },
            { kana: "ケ", romaji: "ke" },
            { kana: "コ", romaji: "ko" },
        ],
        [
            { kana: "サ", romaji: "sa" },
            { kana: "シ", romaji: "shi" },
            { kana: "ス", romaji: "su" },
            { kana: "セ", romaji: "se" },
            { kana: "ソ", romaji: "so" },
        ],
        [
            { kana: "タ", romaji: "ta" },
            { kana: "チ", romaji: "chi" },
            { kana: "ツ", romaji: "tsu" },
            { kana: "テ", romaji: "te" },
            { kana: "ト", romaji: "to" },
        ],
        [
            { kana: "ナ", romaji: "na" },
            { kana: "ニ", romaji: "ni" },
            { kana: "ヌ", romaji: "nu" },
            { kana: "ネ", romaji: "ne" },
            { kana: "ノ", romaji: "no" },
        ],
        [
            { kana: "ハ", romaji: "ha" },
            { kana: "ヒ", romaji: "hi" },
            { kana: "フ", romaji: "fu" },
            { kana: "ヘ", romaji: "he" },
            { kana: "ホ", romaji: "ho" },
        ],
        [
            { kana: "マ", romaji: "ma" },
            { kana: "ミ", romaji: "mi" },
            { kana: "ム", romaji: "mu" },
            { kana: "メ", romaji: "me" },
            { kana: "モ", romaji: "mo" },
        ],
        [
            { kana: "ヤ", romaji: "ya" },
            null,
            { kana: "ユ", romaji: "yu" },
            null,
            { kana: "ヨ", romaji: "yo" },
        ],
        [
            { kana: "ラ", romaji: "ra" },
            { kana: "リ", romaji: "ri" },
            { kana: "ル", romaji: "ru" },
            { kana: "レ", romaji: "re" },
            { kana: "ロ", romaji: "ro" },
        ],
        [
            { kana: "ワ", romaji: "wa" },
            null,
            null,
            null,
            { kana: "ヲ", romaji: "wo" },
        ],
        [
            { kana: "ン", romaji: "n" },
            null,
            null,
            null,
            null,
        ],
    ],

    dakuten: [
        [
            { kana: "が", romaji: "ga" },
            { kana: "ぎ", romaji: "gi" },
            { kana: "ぐ", romaji: "gu" },
            { kana: "げ", romaji: "ge" },
            { kana: "ご", romaji: "go" },
        ],
        [
            { kana: "ざ", romaji: "za" },
            { kana: "じ", romaji: "ji" },
            { kana: "ず", romaji: "zu" },
            { kana: "ぜ", romaji: "ze" },
            { kana: "ぞ", romaji: "zo" },
        ],
        [
            { kana: "だ", romaji: "da" },
            { kana: "ぢ", romaji: "ji" },
            { kana: "づ", romaji: "zu" },
            { kana: "で", romaji: "de" },
            { kana: "ど", romaji: "do" },
        ],
        [
            { kana: "ば", romaji: "ba" },
            { kana: "び", romaji: "bi" },
            { kana: "ぶ", romaji: "bu" },
            { kana: "べ", romaji: "be" },
            { kana: "ぼ", romaji: "bo" },
        ],
    ],

    handakuten: [
        [
            { kana: "ぱ", romaji: "pa" },
            { kana: "ぴ", romaji: "pi" },
            { kana: "ぷ", romaji: "pu" },
            { kana: "ぺ", romaji: "pe" },
            { kana: "ぽ", romaji: "po" },
        ],
    ],

    combinations: [
        [
            { kana: "きゃ", romaji: "kya" },
            { kana: "きゅ", romaji: "kyu" },
            { kana: "きょ", romaji: "kyo" },
        ],
        [
            { kana: "しゃ", romaji: "sha" },
            { kana: "しゅ", romaji: "shu" },
            { kana: "しょ", romaji: "sho" },
        ],
        [
            { kana: "ちゃ", romaji: "cha" },
            { kana: "ちゅ", romaji: "chu" },
            { kana: "ちょ", romaji: "cho" },
        ],
        [
            { kana: "にゃ", romaji: "nya" },
            { kana: "にゅ", romaji: "nyu" },
            { kana: "にょ", romaji: "nyo" },
        ],
        [
            { kana: "ひゃ", romaji: "hya" },
            { kana: "ひゅ", romaji: "hyu" },
            { kana: "ひょ", romaji: "hyo" },
        ],
        [
            { kana: "みゃ", romaji: "mya" },
            { kana: "みゅ", romaji: "myu" },
            { kana: "みょ", romaji: "myo" },
        ],
        [
            { kana: "りゃ", romaji: "rya" },
            { kana: "りゅ", romaji: "ryu" },
            { kana: "りょ", romaji: "ryo" },
        ],
    ],
};