export const LANGUAGES = [
    { code: "af", name: "Afrikaans", flag: "🇿🇦", countryCode: "za" },
    { code: "sq", name: "Albanian", flag: "🇦🇱", countryCode: "al" },
    { code: "ar", name: "Arabic", flag: "🇸🇦", countryCode: "sa" },
    { code: "hy", name: "Armenian", flag: "🇦🇲", countryCode: "am" },
    { code: "az", name: "Azerbaijani", flag: "🇦🇿", countryCode: "az" },
    { code: "eu", name: "Basque", flag: "🇪🇸", countryCode: "es" },
    { code: "be", name: "Belarusian", flag: "🇧🇾", countryCode: "by" },
    { code: "bn", name: "Bengali", flag: "🇧🇩", countryCode: "bd" },
    { code: "bs", name: "Bosnian", flag: "🇧🇦", countryCode: "ba" },
    { code: "bg", name: "Bulgarian", flag: "🇧🇬", countryCode: "bg" },
    { code: "ca", name: "Catalan", flag: "🇪🇸", countryCode: "es" },
    { code: "zh", name: "Chinese", flag: "🇨🇳", countryCode: "cn" },
    { code: "hr", name: "Croatian", flag: "🇭🇷", countryCode: "hr" },
    { code: "cs", name: "Czech", flag: "🇨🇿", countryCode: "cz" },
    { code: "da", name: "Danish", flag: "🇩🇰", countryCode: "dk" },
    { code: "nl", name: "Dutch", flag: "🇳🇱", countryCode: "nl" },
    { code: "en", name: "English", flag: "🇺🇸", countryCode: "us" },
    { code: "et", name: "Estonian", flag: "🇪🇪", countryCode: "ee" },
    { code: "fi", name: "Finnish", flag: "🇫🇮", countryCode: "fi" },
    { code: "fr", name: "French", flag: "🇫🇷", countryCode: "fr" },
    { code: "gl", name: "Galician", flag: "🇪🇸", countryCode: "es" },
    { code: "ka", name: "Georgian", flag: "🇬🇪", countryCode: "ge" },
    { code: "de", name: "German", flag: "🇩🇪", countryCode: "de" },
    { code: "el", name: "Greek", flag: "🇬🇷", countryCode: "gr" },
    { code: "gu", name: "Gujarati", flag: "🇮🇳", countryCode: "in" },
    { code: "he", name: "Hebrew", flag: "🇮🇱", countryCode: "il" },
    { code: "hi", name: "Hindi", flag: "🇮🇳", countryCode: "in" },
    { code: "hu", name: "Hungarian", flag: "🇭🇺", countryCode: "hu" },
    { code: "is", name: "Icelandic", flag: "🇮🇸", countryCode: "is" },
    { code: "id", name: "Indonesian", flag: "🇮🇩", countryCode: "id" },
    { code: "ga", name: "Irish", flag: "🇮🇪", countryCode: "ie" },
    { code: "it", name: "Italian", flag: "🇮🇹", countryCode: "it" },
    { code: "ja", name: "Japanese", flag: "🇯🇵", countryCode: "jp" },
    { code: "kn", name: "Kannada", flag: "🇮🇳", countryCode: "in" },
    { code: "kk", name: "Kazakh", flag: "🇰🇿", countryCode: "kz" },
    { code: "ko", name: "Korean", flag: "🇰🇷", countryCode: "kr" },
    { code: "lv", name: "Latvian", flag: "🇱🇻", countryCode: "lv" },
    { code: "lt", name: "Lithuanian", flag: "🇱🇹", countryCode: "lt" },
    { code: "mk", name: "Macedonian", flag: "🇲🇰", countryCode: "mk" },
    { code: "ms", name: "Malay", flag: "🇲🇾", countryCode: "my" },
    { code: "ml", name: "Malayalam", flag: "🇮🇳", countryCode: "in" },
    { code: "mr", name: "Marathi", flag: "🇮🇳", countryCode: "in" },
    { code: "mn", name: "Mongolian", flag: "🇲🇳", countryCode: "mn" },
    { code: "ne", name: "Nepali", flag: "🇳🇵", countryCode: "np" },
    { code: "no", name: "Norwegian", flag: "🇳🇴", countryCode: "no" },
    { code: "fa", name: "Persian", flag: "🇮🇷", countryCode: "ir" },
    { code: "pl", name: "Polish", flag: "🇵🇱", countryCode: "pl" },
    { code: "pt", name: "Portuguese", flag: "🇵🇹", countryCode: "pt" },
    { code: "pa", name: "Punjabi", flag: "🇮🇳", countryCode: "in" },
    { code: "ro", name: "Romanian", flag: "🇷🇴", countryCode: "ro" },
    { code: "ru", name: "Russian", flag: "🇷🇺", countryCode: "ru" },
    { code: "sr", name: "Serbian", flag: "🇷🇸", countryCode: "rs" },
    { code: "sk", name: "Slovak", flag: "🇸🇰", countryCode: "sk" },
    { code: "sl", name: "Slovenian", flag: "🇸🇮", countryCode: "si" },
    { code: "es", name: "Spanish", flag: "🇪🇸", countryCode: "es" },
    { code: "sw", name: "Swahili", flag: "🇰🇪", countryCode: "ke" },
    { code: "sv", name: "Swedish", flag: "🇸🇪", countryCode: "se" },
    { code: "ta", name: "Tamil", flag: "🇮🇳", countryCode: "in" },
    { code: "te", name: "Telugu", flag: "🇮🇳", countryCode: "in" },
    { code: "th", name: "Thai", flag: "🇹🇭", countryCode: "th" },
    { code: "tr", name: "Turkish", flag: "🇹🇷", countryCode: "tr" },
    { code: "uk", name: "Ukrainian", flag: "🇺🇦", countryCode: "ua" },
    { code: "ur", name: "Urdu", flag: "🇵🇰", countryCode: "pk" },
    { code: "uz", name: "Uzbek", flag: "🇺🇿", countryCode: "uz" },
    { code: "vi", name: "Vietnamese", flag: "🇻🇳", countryCode: "vn" },
    { code: "cy", name: "Welsh", flag: "🏴", countryCode: "gb-wls" },
];

export function getLanguageFlagUrl(language) {
    if (!language?.countryCode) return "";
    return `https://flagcdn.com/w40/${language.countryCode}.png`;
}