export const lessonStepTemplates = {
    intro: {
        type: "intro",
        title: "Intro",
        content: {
            headline: "",
            text: "",
        },
    },
    vocabulary: {
        type: "vocabulary",
        title: "Vocabulary",
        items: [
            {
                text: "",
                translation: "",
                pronunciation: "",
                audio: null,
                audioPreview: "",
                image: null,
                imagePreview: "",
                note: "",
                example: {
                    english: "",
                    translation: "",
                },
            },
        ],
    },
    theory: {
        type: "theory",
        title: "Mini Theory",
        content: {
            text: "",
        },
    },
    "multiple-choice": {
        type: "multiple-choice",
        title: "Multiple Choice",
        question: "",
        options: ["", "", "", ""],
        answer: "",
        explanation: "",
    },
    listening: {
        type: "listening",
        title: "Listening",
        audio: "",
        question: "",
        options: ["", "", "", ""],
        answer: "",
        explanation: "",
    },
    speaking: {
        type: "speaking",
        title: "Speaking",
        prompt: "",
        targetText: "",
        hint: "",
    },
    conversation: {
        type: "conversation",
        title: "Conversation",
        messages: [
            { from: "bot", text: "" },
            { from: "user", options: ["", ""] },
        ],
    },
    "fill-in-the-blank": {
        type: "fill-in-the-blank",
        title: "Complete the sentence",
        prompt: "",
        sentence: "",
        answer: "",
        acceptableAnswers: [""],
        explanation: "",
    },
    "letter-bank": {
        type: "letter-bank",
        title: "Build the word",
        prompt: "",
        template: "",
        letters: ["", "", "", ""],
        answer: "",
        explanation: "",
    },
    unscramble: {
        type: "unscramble",
        title: "Unscramble",
        prompt: "",
        words: ["", "", ""],
        answer: "",
        explanation: "",
    },
    "match-pairs": {
        type: "match-pairs",
        title: "Match pairs",
        prompt: "",
        pairs: [
            { left: "", right: "" },
            { left: "", right: "" },
        ],
        explanation: "",
    },
    "translate-short-answer": {
        type: "translate-short-answer",
        title: "Translate",
        prompt: "",
        sourceText: "",
        answer: "",
        acceptableAnswers: [""],
        explanation: "",
    },
    "listening-type": {
        type: "listening-type",
        title: "Listening and type",
        prompt: "",
        audio: "",
        answer: "",
        acceptableAnswers: [""],
        explanation: "",
    },
    "image-choice": {
        type: "image-choice",
        title: "Image choice",
        prompt: "",
        image: "",
        options: ["", "", "", ""],
        answer: "",
        explanation: "",
    },
};